---
- name: Ensure etcd configuration directory exists
  file:
    path: "{{ etcd_config_dir }}"
    state: directory

- name: Ensure etcd data directory exists
  file:
    path: "{{ etcd_data_dir }}"
    state: directory
    owner: "etcd"
    group: "etcd"
    mode: 0755

- name: Enable etcd service
  service:
    name: "etcd"
    enabled: true

- name: Create systemd override directory
  file:
    path: "{{ etcd_systemd_dir }}"
    state: "directory"

- name: Drop etcd systemd configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: 0644
  # notify:
  #   - "Reload systemd daemon"
  #   - "Restart etcd service"
  register: _systemd_conf
  with_items:
    - { src: "systemd-etcd-override.conf.j2", dest: "/etc/systemd/system/etcd.service.d/override.conf" }
    - { src: "systemd-etcd.conf.j2", dest: "{{ etcd_config_dir }}/etcd.conf" }

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: _systemd_conf.changed

- name: Restart etcd service
  service:
    name: etcd
    state: restarted
  when: _systemd_conf.changed

- name: Verify etcd cluster
  command: etcdctl cluster-health
  register: etcd_health
  failed_when: etcd_health.rc != 0
  until: etcd_health is success
  retries: 5
  delay: 2
  when: inventory_hostname == groups[etcd_cluster_group][0]
...
